[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#00b9f1"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#0f172a"
